<?php

// Home page
$app->get('/', "trains\Controller\HomeController::indexAction")
    ->bind('home');

// Locomotives
// ===========

// Collection page
$app->get('/locomotives', "trains\Controller\LocomotiveController::collectionAction")
    ->bind('locomotives');

// Cars
// ===========

// Collection page
$app->get('/cars', "trains\Controller\CarController::collectionAction")
    ->bind('cars');

// Collection generated by generator page
$app->get('/cars/generator', "trains\Controller\CarController::collectionGeneratorAction")
    ->bind('carsgenerator');

// Car Types page
$app->get('/car/types', "trains\Controller\CarController::typeCollectionAction")
    ->bind('cartypes');

// Car By Types page
$app->get('/cars/by/type/{id}', "trains\Controller\CarController::byTypeCollectionAction")
    ->bind('cars_by_type');

// Car create
$app->get('/car/create/random', "trains\Controller\CarController::createRandomAction")
    ->bind('car_random_create');
/* DEPREC : Keep just to see how to call middleware event
$app->get('/car/create/random', "trains\Controller\CarController::createRandomAction")
    ->bind('car_random_create')
    ->after(function () use ($app) {
        // here is a message creation using middleware
        $messageSender = new trains\Message\RollingStockMessageSender();
        $messageSender->carCreateMessage($app);
    });
*/


// Metier
// ======
$app->get('/metier/rollingstock/create', "trains\Controller\MetierController::rollingStockCreateAction")
    ->bind('metier_rolling_stock_creation')
;

